import os
import pickle
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# ---------------------------------------------------------------------------
# Google Drive API Authentication Setup (credentials.json)
#
# This script uses OAuth 2.0 to authenticate with Google Drive.
# The file `googleDriveFileSyncCredentials.json` is NOT generated by this script automatically.
#
# To generate `googleDriveFileSyncCredentials.json`:
# 1. Go to Google Cloud Console: https://console.cloud.google.com/
# 2. Create or select a project.
# 3. Enable the "Google Drive API".
# 4. Navigate to: Google Auth Platform → Clients
# 5. Click "Create Client".
# 6. Choose Application Type: "Desktop App".
# 7. Create the client and IMMEDIATELY download the JSON file.
# 8. Rename the downloaded file to `googleDriveFileSyncCredentials.json`.
# 9. Place `googleDriveFileSyncCredentials.json` in the same directory as this script.
#
# NOTE:
# - Google allows downloading googleDriveFileSyncCredentials.json only at creation time.
# - If the file is lost, create a new OAuth client and download again.
# - Do NOT commit googleDriveFileSyncCredentials.json or token.pickle to version control.
#
# This script will generate `token.pickle` automatically on first run
# after you log in via the browser.
# ---------------------------------------------------------------------------



# ---------------- CONFIG ----------------
# LOCAL_FOLDER = /path/to/your/local/folder"
LOCAL_FOLDER=""
# DRIVE_FOLDER_NAME = "Folder Name"
DRIVE_FOLDER_NAME=""
SCOPES = ['https://www.googleapis.com/auth/drive']
# ----------------------------------------


def authenticate():
    creds = None

    if os.path.exists("token.pickle"):
        with open("token.pickle", "rb") as token:
            creds = pickle.load(token)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                "googleDriveFileSyncCredentials.json", SCOPES
            )
            creds = flow.run_local_server(port=0)

        with open("token.pickle", "wb") as token:
            pickle.dump(creds, token)

    return build("drive", "v3", credentials=creds)


def get_or_create_folder(service, folder_name):
    query = (
        f"name='{folder_name}' and "
        f"mimeType='application/vnd.google-apps.folder' and "
        f"trashed=false"
    )

    response = service.files().list(q=query, fields="files(id, name)").execute()
    files = response.get("files", [])

    if files:
        return files[0]["id"]

    file_metadata = {
        "name": folder_name,
        "mimeType": "application/vnd.google-apps.folder",
    }

    folder = service.files().create(
        body=file_metadata, fields="id"
    ).execute()

    return folder["id"]


def get_existing_filenames(service, folder_id):
    query = f"'{folder_id}' in parents and trashed=false"
    response = service.files().list(
        q=query, fields="files(name)"
    ).execute()

    return {file["name"] for file in response.get("files", [])}


def upload_files(service, folder_id, local_folder):
    existing_files = get_existing_filenames(service, folder_id)

    for filename in os.listdir(local_folder):
        filepath = os.path.join(local_folder, filename)

        if not os.path.isfile(filepath):
            continue

        if filename in existing_files:
            print(f"Skipping (already exists): {filename}")
            continue

        media = MediaFileUpload(filepath, resumable=True)

        file_metadata = {
            "name": filename,
            "parents": [folder_id]
        }

        service.files().create(
            body=file_metadata,
            media_body=media,
            fields="id"
        ).execute()

        print(f"Uploaded: {filename}")


def main():
    service = authenticate()
    folder_id = get_or_create_folder(service, DRIVE_FOLDER_NAME)
    upload_files(service, folder_id, LOCAL_FOLDER)


if __name__ == "__main__":
    main()
